name: agents

services:

  sindit_influx_db:
    extends:
      file: docker-compose.databases.yml
      service: sindit_influx_db
    ports:
      - '8086:8086'

  sindit_neo4j_kg:
    extends:
      file: docker-compose.databases.yml
      service: sindit_neo4j_kg
    ports:
      - 7474:7474
      - 7687:7687

  sindit_minio_s3:
    extends:
      file: docker-compose.databases.yml
      service: sindit_minio_s3
    ports:
      - "9000:9000"
      - "9099:9099"

  zookeeper:
    image: 'zookeeper:3.7'
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mqtt_kafka_bridge:
    build:
      context: .
      dockerfile: docker/mqttKafka.dockerfile
    image: kafka_bridge
    depends_on:
      - kafka

  
  # Ollama container 
  llm:
    build:
      context: .
      dockerfile: docker/ollama.dockerfile
    # Container name is used to access ollama services from the notebook
    container_name: llm
    # Extra host is used to reach ollama services from the notebook,
    # otherwise with localhost will simply give connection error.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Let ollama run on GPU, if you do not have one we suggest to comment/remove this part.
    # The documentation to install the correct drivers can be found at https://hub.docker.com/r/ollama/ollama.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    tty: true
    volumes: # Ollama stores the installed model 
      - ollama:/root/.ollama
    restart: unless-stopped

  statistics:
    container_name: statistics
    build:
      context: .
      dockerfile: docker/statistics.dockerfile
    image: stats
    stdin_open: true
    tty: true
    ports:
      - "5003:5003"
  
  neodash:
    build:
      context: .
      dockerfile: docker/neodash.dockerfile
    image: neodash
    container_name: neodash
    stdin_open: true
    tty: true

volumes:
  sindit-minio-s3-volume:
  sindit-neo4j-conf-volume:
  sindit-neo4j-logs-volume:
  sindit-neo4j-data-volume:
  sindit-influx-db-data-volume:
  sindit-influx-db-config-volume:
  sindit-kafka-data-volume:
  ollama: